
package AdminInterface;

import Interfaces.welcomepage;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import utility.DBClass;


public class AdminDashboard extends javax.swing.JFrame {
 DBClass dob;
    public AdminDashboard() {
        initComponents();
         dob = new DBClass();
         startRealTimeMemberCount();
         updateMemberCount();
         updateBookCopies();
         updateBookCopies();
         updateIssueBookCount();
         updateReturnBookCount();
          showDate();
         showTime();
       tableload();
        this.setExtendedState(AdminDashboard.MAXIMIZED_BOTH);
            
    }
    
  public void startRealTimeMemberCount() {
    Timer timer = new Timer(1000, new ActionListener() { // 1000ms = 1 second
        @Override
        public void actionPerformed(ActionEvent e) {
            updateData();
        }
    });
    timer.start(); // Start the timer
}   
   
  private void updateData() {
        updateBookCopies();
        updateMemberCount();
        updateStaffCount();
        updateIssueBookCount();
        updateReturnBookCount();
    }
  
   private void updateMemberCount() {
        try {
            dob.connect();
            String sql = "SELECT COUNT(*) AS total FROM members";

            ResultSet rs = dob.selectRecord(sql);

            if (rs.next()) {
                int totalMembers = rs.getInt("total");
                txtnoofmember.setText(String.valueOf(totalMembers));
            }
        } catch (SQLException e) {
            txtnoofmember.setText("Error");
        }
    }
 
private void updateBookCopies() {
        try {
            dob.connect(); // Connect to the database
            String sql = "SELECT SUM(No_Of_Copies) AS total FROM add_books";

            ResultSet rs = dob.selectRecord(sql);

            if (rs.next()) {
                int totalCopies = rs.getInt("total");
                txtnoofbooks.setText(String.valueOf(totalCopies));
            }
        } catch (SQLException e) {
            txtnoofbooks.setText("Error");
        }
    }

 private void updateStaffCount() {
        try {
            dob.connect();
            String sql = "SELECT COUNT(*) AS total FROM staff_details";

            ResultSet rs = dob.selectRecord(sql);

            if (rs.next()) {
                int totalStaff = rs.getInt("total");
                txtnoofstaff.setText(String.valueOf(totalStaff));
            }
        } catch (SQLException e) {
            txtnoofstaff.setText("Error");
        }
    }
 
 private void updateIssueBookCount() {
        try {
            dob.connect();
            String sql = "SELECT COUNT(*) AS total FROM issue_book ";

            ResultSet rs = dob.selectRecord(sql);

            if (rs.next()) {
                int totalMembers = rs.getInt("total");
                txtnoofissue.setText(String.valueOf(totalMembers));
            }
        } catch (SQLException e) {
            txtnoofissue.setText("Error");
        }
    }
 
 private void updateReturnBookCount() {
        try {
            dob.connect();
            String sql = "SELECT COUNT(*) AS total FROM issue_book WHERE Return_Book = '"+"Yes"+"'";

            ResultSet rs = dob.selectRecord(sql);

            if (rs.next()) {
                int totalMembers = rs.getInt("total");
                txtretunbook.setText(String.valueOf(totalMembers));
            }
        } catch (SQLException e) {
            txtretunbook.setText("Error");
        }
    }

     public void showDate(){
    Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyyy");
    String Dat = s.format(d);
    txtdate.setText(Dat);
    }
     
     
     
      public void showTime(){
   new Timer(0,new ActionListener() {
       @Override
       public void actionPerformed(ActionEvent e) {
            Date d = new Date();
            SimpleDateFormat s = new SimpleDateFormat("hh-mm-ss");
            String Tim = s.format(d);
    txttime.setText(Tim);

       }
   }).start();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Staff_txt_grp = new javax.swing.ButtonGroup();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel11 = new javax.swing.JLabel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        txtdate = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txttime = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtnoofmember = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtnoofbooks = new javax.swing.JLabel();
        txtnoofstaff = new javax.swing.JLabel();
        txtnoofissue = new javax.swing.JLabel();
        txtretunbook = new javax.swing.JLabel();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        btnsearchbooks = new javax.swing.JToggleButton();
        btnissuebook = new javax.swing.JToggleButton();
        btnissuebooks = new javax.swing.JToggleButton();
        btnreturnbooks1 = new javax.swing.JToggleButton();
        btnreturnbooks2 = new javax.swing.JToggleButton();
        btnreturnbooks = new javax.swing.JToggleButton();
        btnlogout = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtbookID = new javax.swing.JTextField();
        txtcategory = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtauthor = new javax.swing.JTextField();
        txtpublisher = new javax.swing.JTextField();
        txtprice = new javax.swing.JTextField();
        txtno = new javax.swing.JTextField();
        txtISBN = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        btnadd1 = new javax.swing.JButton();
        btnadd2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        btncancel2 = new javax.swing.JButton();
        btncancel3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableadmin = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtbookID1 = new javax.swing.JTextField();
        btnadd3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        kGradientPanel1.setkEndColor(new java.awt.Color(0, 153, 153));
        kGradientPanel1.setkStartColor(new java.awt.Color(153, 255, 255));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Bookmark.png"))); // NOI18N
        jLabel11.setText("Library Management System");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(319, 319, 319))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        kGradientPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        kGradientPanel2.setkEndColor(new java.awt.Color(0, 153, 153));
        kGradientPanel2.setkStartColor(new java.awt.Color(153, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Installment Plan.png"))); // NOI18N

        txtdate.setBackground(new java.awt.Color(0, 0, 0));
        txtdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtdate.setText("Date");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Clock.png"))); // NOI18N

        txttime.setBackground(new java.awt.Color(0, 0, 0));
        txttime.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txttime.setText("Time");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Total of Members :");

        txtnoofmember.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        txtnoofmember.setForeground(new java.awt.Color(255, 255, 0));
        txtnoofmember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Management1.png"))); // NOI18N
        txtnoofmember.setText("000");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Total of Books :");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Total of Staff :");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Total of Issue Books:");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Total of Return Books:");

        txtnoofbooks.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        txtnoofbooks.setForeground(new java.awt.Color(255, 255, 0));
        txtnoofbooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Book Shelf2.png"))); // NOI18N
        txtnoofbooks.setText("000");

        txtnoofstaff.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        txtnoofstaff.setForeground(new java.awt.Color(255, 255, 0));
        txtnoofstaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Staff1.png"))); // NOI18N
        txtnoofstaff.setText("000");

        txtnoofissue.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        txtnoofissue.setForeground(new java.awt.Color(255, 255, 0));
        txtnoofissue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Borrow Book2.png"))); // NOI18N
        txtnoofissue.setText("000");

        txtretunbook.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        txtretunbook.setForeground(new java.awt.Color(255, 255, 0));
        txtretunbook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Return Book2.png"))); // NOI18N
        txtretunbook.setText("000");

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtdate)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txttime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtnoofmember)))
                .addGap(50, 50, 50)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtnoofbooks)))
                .addGap(46, 46, 46)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtnoofstaff)))
                .addGap(40, 40, 40)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(txtnoofissue)))
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel18)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtretunbook)
                        .addGap(59, 59, 59))))
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnoofmember)
                    .addComponent(txtnoofbooks)
                    .addComponent(txtnoofstaff)
                    .addComponent(txtnoofissue))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtretunbook)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txttime)
                    .addComponent(txtdate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        kGradientPanel3.setkEndColor(new java.awt.Color(0, 255, 255));
        kGradientPanel3.setkStartColor(new java.awt.Color(0, 153, 153));

        btnsearchbooks.setBackground(new java.awt.Color(204, 204, 255));
        Staff_txt_grp.add(btnsearchbooks);
        btnsearchbooks.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnsearchbooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-admin-48.png"))); // NOI18N
        btnsearchbooks.setText("Member  Report");
        btnsearchbooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchbooksActionPerformed(evt);
            }
        });

        btnissuebook.setBackground(new java.awt.Color(204, 204, 255));
        Staff_txt_grp.add(btnissuebook);
        btnissuebook.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnissuebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-borrow-book-48.png"))); // NOI18N
        btnissuebook.setText("Issue Book Report");
        btnissuebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnissuebookActionPerformed(evt);
            }
        });

        btnissuebooks.setBackground(new java.awt.Color(204, 204, 255));
        Staff_txt_grp.add(btnissuebooks);
        btnissuebooks.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnissuebooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/return-book-1-560407.png"))); // NOI18N
        btnissuebooks.setText("Return Book Report");
        btnissuebooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnissuebooksActionPerformed(evt);
            }
        });

        btnreturnbooks1.setBackground(new java.awt.Color(204, 204, 255));
        Staff_txt_grp.add(btnreturnbooks1);
        btnreturnbooks1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnreturnbooks1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-books-48.png"))); // NOI18N
        btnreturnbooks1.setText("Overdue Book Report");
        btnreturnbooks1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreturnbooks1ActionPerformed(evt);
            }
        });

        btnreturnbooks2.setBackground(new java.awt.Color(204, 204, 255));
        Staff_txt_grp.add(btnreturnbooks2);
        btnreturnbooks2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnreturnbooks2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-reports-48.png"))); // NOI18N
        btnreturnbooks2.setText("Financial Report");
        btnreturnbooks2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreturnbooks2ActionPerformed(evt);
            }
        });

        btnreturnbooks.setBackground(new java.awt.Color(204, 204, 255));
        Staff_txt_grp.add(btnreturnbooks);
        btnreturnbooks.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnreturnbooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/staff-48.png"))); // NOI18N
        btnreturnbooks.setText("Staff Details");
        btnreturnbooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreturnbooksActionPerformed(evt);
            }
        });

        btnlogout.setBackground(new java.awt.Color(204, 204, 255));
        Staff_txt_grp.add(btnlogout);
        btnlogout.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-logout-48.png"))); // NOI18N
        btnlogout.setText("Logout");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel3Layout = new javax.swing.GroupLayout(kGradientPanel3);
        kGradientPanel3.setLayout(kGradientPanel3Layout);
        kGradientPanel3Layout.setHorizontalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnreturnbooks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnreturnbooks2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnreturnbooks1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnissuebooks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnissuebook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnsearchbooks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kGradientPanel3Layout.setVerticalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnsearchbooks, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnissuebook, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnissuebooks, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnreturnbooks1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnreturnbooks2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnreturnbooks, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setText("Book Inventory");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("Book ID :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Category :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Name :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Author :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Publisher :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Price :");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("No OF Copies :");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("ISBN :");

        txtbookID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtbookID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtbookIDFocusLost(evt);
            }
        });
        txtbookID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbookIDActionPerformed(evt);
            }
        });

        txtcategory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtcategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcategoryActionPerformed(evt);
            }
        });

        txtname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });

        txtauthor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtauthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtauthorActionPerformed(evt);
            }
        });

        txtpublisher.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtpublisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpublisherActionPerformed(evt);
            }
        });

        txtprice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpriceActionPerformed(evt);
            }
        });

        txtno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnoActionPerformed(evt);
            }
        });

        txtISBN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtISBNActionPerformed(evt);
            }
        });

        btnadd.setBackground(new java.awt.Color(204, 204, 204));
        btnadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Save Close.png"))); // NOI18N
        btnadd.setText("ADD");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnadd1.setBackground(new java.awt.Color(204, 204, 204));
        btnadd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Available Updates.png"))); // NOI18N
        btnadd1.setText("Update");
        btnadd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadd1ActionPerformed(evt);
            }
        });

        btnadd2.setBackground(new java.awt.Color(204, 204, 204));
        btnadd2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Waste.png"))); // NOI18N
        btnadd2.setText("Delete");
        btnadd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadd2ActionPerformed(evt);
            }
        });

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book ID", "Category", "Name", "Author", "Publisher", "Price", "No of Copies", "ISBN"
            }
        ));
        jScrollPane1.setViewportView(table2);

        btncancel2.setBackground(new java.awt.Color(204, 204, 204));
        btncancel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Print.png"))); // NOI18N
        btncancel2.setText("Print Report");
        btncancel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancel2ActionPerformed(evt);
            }
        });

        btncancel3.setBackground(new java.awt.Color(204, 204, 204));
        btncancel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Eye.png"))); // NOI18N
        btncancel3.setText("View Report");
        btncancel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancel3ActionPerformed(evt);
            }
        });

        tableadmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book ID", "Category", "Name", "Author", "Publisher", "Price", "No of Copies", "ISBN"
            }
        ));
        tableadmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableadminMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableadmin);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Book ID");

        txtbookID1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtbookID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbookID1ActionPerformed(evt);
            }
        });

        btnadd3.setBackground(new java.awt.Color(204, 204, 204));
        btnadd3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Broom.png"))); // NOI18N
        btnadd3.setText("Clear");
        btnadd3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadd3ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtcategory, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtauthor, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtpublisher, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtno, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(47, 47, 47)
                                .addComponent(txtbookID, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btncancel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtbookID1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton1)
                                        .addGap(42, 42, 42))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnadd1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnadd2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnadd3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btncancel3)
                        .addGap(8, 8, 8)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(452, 452, 452)
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel19)
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btncancel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtbookID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnadd2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btncancel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnadd1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnadd3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(txtbookID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtcategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtauthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtpublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kGradientPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kGradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnissuebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnissuebookActionPerformed
        // TODO add your handling code here:
         new IssueBookReport().setVisible(true);
    }//GEN-LAST:event_btnissuebookActionPerformed

    private void btnissuebooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnissuebooksActionPerformed
        // TODO add your handling code here:
        new ReturnBookReport().setVisible(true);
    }//GEN-LAST:event_btnissuebooksActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
        setVisible(false);
            new welcomepage().setVisible(true);
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnreturnbooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreturnbooksActionPerformed
        // TODO add your handling code here:
        new StaffManagementReport().setVisible(true);
    }//GEN-LAST:event_btnreturnbooksActionPerformed

    private void btnsearchbooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchbooksActionPerformed
        // TODO add your handling code here:
        new MemberManagementReport().setVisible(true);
    }//GEN-LAST:event_btnsearchbooksActionPerformed

    private void btnreturnbooks1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreturnbooks1ActionPerformed
        // TODO add your handling code here:
        new OverdueBookReport().setVisible(true);
    }//GEN-LAST:event_btnreturnbooks1ActionPerformed

    private void btnreturnbooks2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreturnbooks2ActionPerformed
        // TODO add your handling code here:
         new FinancialReport().setVisible(true);
    }//GEN-LAST:event_btnreturnbooks2ActionPerformed

    private void txtbookIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtbookIDFocusLost
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            DBClass dob=new DBClass();
            dob.connect();
            String sql="select *from add_books where Book_ID='"+txtbookID.getText()+"'";
            // System.out.println(sql);
            ResultSet rs=dob.selectRecord(sql);
            while(rs.next())
            {

                txtcategory.setText(rs.getString("Category"));
                txtname.setText(rs.getString("Name"));
                txtauthor.setText(rs.getString("Author"));
                txtpublisher.setText(rs.getString("Publisher"));
                txtprice.setText(rs.getString("Price"));
                txtno.setText(rs.getString("No_of_Copies"));
                txtISBN.setText(rs.getString("ISBN"));

                //txtWorkerTitle.setText(rs.getString("WORKER_TITLE"));
            }
            dob.closeCon();

        } catch (SQLException ex) {
            Logger.getLogger(MemberManagementReport.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtbookIDFocusLost

    private void txtbookIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbookIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbookIDActionPerformed

    private void txtcategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcategoryActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtauthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtauthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtauthorActionPerformed

    private void txtpublisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpublisherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpublisherActionPerformed

    private void txtpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpriceActionPerformed

    private void txtnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnoActionPerformed

    private void txtISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtISBNActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:

        try {
            String sql = "insert into add_books(Category, Name, Author, Publisher, Price, No_of_Copies,ISBN )"
            + "values('"+txtcategory.getText()+"','"+txtname.getText() +"','"+txtauthor.getText()+"','"+txtpublisher.getText()+"','"+txtprice.getText()+"','"+txtno.getText()+"','"+txtISBN.getText()+"')";
            dob.connect();
            dob.insert(sql);
            dob.closeCon();
            tableload();

            txtbookID.setText("");
            txtcategory.setText("");
            txtname.setText("");
            txtauthor.setText("");
            txtpublisher.setText("");
            txtprice.setText("");
            txtno.setText("");
            txtISBN.setText("");

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnadd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadd1ActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "update add_books set Category = '" + txtcategory.getText() + "', Name = '"
            + txtname.getText() + "',Author = '" + txtauthor.getText() + "', Publisher = '" + txtpublisher.getText() + "',"
            + "Price = '" + txtprice.getText() + "', No_of_Copies= '" + txtno.getText() + "', ISBN = '" + txtISBN.getText() + "' Where Book_ID = " + txtbookID.getText();
            dob.connect();
            dob.update(sql);
            dob.closeCon();

            tableload();

            txtbookID.setText("");
            txtcategory.setText("");
            txtname.setText("");
            txtauthor.setText("");
            txtpublisher.setText("");
            txtprice.setText("");
            txtno.setText("");
            txtISBN.setText("");

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnadd1ActionPerformed

    private void btnadd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadd2ActionPerformed
        // TODO add your handling code here:
        try {
            int res = JOptionPane.showConfirmDialog(null, "Do you want to Delete?",null,JOptionPane.YES_NO_OPTION);
            if(res == JOptionPane.YES_NO_OPTION){

                String sql = "delete from add_books where Book_ID = " + txtbookID.getText();
                dob.connect();
                dob.delete(sql);
                dob.closeCon();
                //JOptionPane.showMessageDialog(null, "Success...!");
                tableload();

                txtbookID.setText("");
                txtcategory.setText("");
                txtname.setText("");
                txtauthor.setText("");
                txtpublisher.setText("");
                txtprice.setText("");
                txtno.setText("");
                txtISBN.setText("");

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            // meken delete krn ek
        }
    }//GEN-LAST:event_btnadd2ActionPerformed

    private void btncancel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancel2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncancel2ActionPerformed

    private void btncancel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancel3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncancel3ActionPerformed

    private void tableadminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableadminMouseClicked
        // TODO add your handling code here:
        int r = tableadmin.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tableadmin.getModel();

        txtbookID.setText(model.getValueAt(r, 0).toString());
        txtcategory.setText(model.getValueAt(r, 1).toString());
        txtname.setText(model.getValueAt(r, 2).toString());
        txtauthor.setText(model.getValueAt(r, 3).toString());
        txtpublisher.setText(model.getValueAt(r, 4).toString());
        txtprice.setText(model.getValueAt(r, 5).toString());
        txtno.setText(model.getValueAt(r, 6).toString());
        txtISBN.setText(model.getValueAt(r, 7).toString());
    }//GEN-LAST:event_tableadminMouseClicked

    private void txtbookID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbookID1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbookID1ActionPerformed

    private void btnadd3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadd3ActionPerformed
        // TODO add your handling code here:
        txtbookID.setText("");
        txtcategory.setText("");
        txtname.setText("");
        txtauthor.setText("");
        txtpublisher.setText("");
        txtprice.setText("");
        txtno.setText("");
        txtISBN.setText("");
    }//GEN-LAST:event_btnadd3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         String bookId = txtbookID1.getText(); // Get the book ID from the label or text field
    DefaultTableModel model = (DefaultTableModel) table2.getModel(); // Get the table model
    model.setRowCount(0); // Clear existing rows
        try {
             DBClass dob=new DBClass();
            dob.connect();
            String sql="select *from add_books where Book_ID='"+txtbookID1.getText()+"'";
            // System.out.println(sql);
            ResultSet rs=dob.selectRecord(sql);
            while(rs.next())
            {
                
            int id = rs.getInt("Book_ID");
            String category = rs.getString("Category");
            String name = rs.getString("Name");
            String author = rs.getString("Author");
             String puplisher= rs.getString("Publisher");
            String price = rs.getString("Price");
           int no = rs.getInt("No_of_Copies");
            String isbn = rs.getString("ISBN");

            // Add data to the table
            model.addRow(new Object[]{id,category,name,author,puplisher, price,no,isbn});

               

                //txtWorkerTitle.setText(rs.getString("WORKER_TITLE"));
            }
            dob.closeCon();
            
        } catch (SQLException e) {
             JOptionPane.showMessageDialog(this, "Error retrieving data: " + e.getMessage());
        }
  
        
    }//GEN-LAST:event_jButton1ActionPerformed

    
    public void tableload() {
        try {
            String sql = "select * from add_books";
            dob.connect();
            ResultSet rs = dob.selectRecord(sql);
            DefaultTableModel model = (DefaultTableModel) tableadmin.getModel();
            model.setRowCount(0);
            
            while (rs.next()) {
                String a = rs.getString("Book_ID");
                String b = rs.getString("Category");
                String c = rs.getString("Name"); 
                 String d = rs.getString("Author");
                String e = rs.getString("Publisher");
                String f = rs.getString("Price");
                String g = rs.getString("NO_of_Copies");
                String h = rs.getString("ISBN");
                
                model.addRow(new Object[]{a,b,c,d,e,f,g,h});
                
            }
            
        } catch (Exception e) {
            
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Staff_txt_grp;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnadd1;
    private javax.swing.JButton btnadd2;
    private javax.swing.JButton btnadd3;
    private javax.swing.JButton btncancel2;
    private javax.swing.JButton btncancel3;
    private javax.swing.JToggleButton btnissuebook;
    private javax.swing.JToggleButton btnissuebooks;
    private javax.swing.JToggleButton btnlogout;
    private javax.swing.JToggleButton btnreturnbooks;
    private javax.swing.JToggleButton btnreturnbooks1;
    private javax.swing.JToggleButton btnreturnbooks2;
    private javax.swing.JToggleButton btnsearchbooks;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private keeptoo.KGradientPanel kGradientPanel3;
    private javax.swing.JTable table2;
    private javax.swing.JTable tableadmin;
    private javax.swing.JTextField txtISBN;
    private javax.swing.JTextField txtauthor;
    private javax.swing.JTextField txtbookID;
    private javax.swing.JTextField txtbookID1;
    private javax.swing.JTextField txtcategory;
    private javax.swing.JLabel txtdate;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtno;
    private javax.swing.JLabel txtnoofbooks;
    private javax.swing.JLabel txtnoofissue;
    private javax.swing.JLabel txtnoofmember;
    private javax.swing.JLabel txtnoofstaff;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtpublisher;
    private javax.swing.JLabel txtretunbook;
    private javax.swing.JLabel txttime;
    // End of variables declaration//GEN-END:variables
}
