/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AdminInterface;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utility.DBClass;

/**
 *
 * @author User
 */
public class StaffManagementReport extends javax.swing.JFrame {
DBClass dob; 
    /**
     * 
     * Creates new form MemberManagementReport
     */
    public StaffManagementReport() {
        initComponents();
       dob = new DBClass();
       tableload();
    }    
    
    public void tableload() {
        try {
            String sql = "select * from staff_details";
            dob.connect();
            ResultSet rs = dob.selectRecord(sql);
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            model.setRowCount(0);
            
            while (rs.next()) {
                String a = rs.getString("Staff_ID");
                String b = rs.getString("First_Name"); 
                String c = rs.getString("Last_Name"); 
                 String d = rs.getString("Address");
                String e = rs.getString("Birthday");
                String f = rs.getString("Phone");
                String g = rs.getString("Gender");
                String h = rs.getString("NIC");
                String i = rs.getString("Username");
                String j = rs.getString("Password");
                
                model.addRow(new Object[]{a,b,c,d,e,f,g,h,i,j});
                
            }
            
        } catch (Exception e) {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        txtuname = new javax.swing.JTextField();
        txtsnic = new javax.swing.JTextField();
        txtsgender = new javax.swing.JTextField();
        txtsphone = new javax.swing.JTextField();
        txtsbd = new javax.swing.JTextField();
        txtsaddress = new javax.swing.JTextField();
        txtlastname = new javax.swing.JTextField();
        txtfirstname = new javax.swing.JTextField();
        txtstaffid = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        txtpword = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        btnsave9 = new javax.swing.JButton();
        btnsave10 = new javax.swing.JButton();
        btnsave11 = new javax.swing.JButton();
        btnclear3 = new javax.swing.JButton();
        btnclose3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnsave12 = new javax.swing.JButton();
        jLabel50 = new javax.swing.JLabel();
        txtmemberID4 = new javax.swing.JTextField();
        btnsave13 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(250, 100));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel37.setText("Staff Details");

        jLabel38.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel38.setText("Staff ID :");

        jLabel40.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel40.setText("First Name :");

        jLabel39.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel39.setText("Last Name :");

        jLabel42.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel42.setText("Address :");

        jLabel47.setForeground(new java.awt.Color(204, 204, 204));
        jLabel47.setText("(Please enter your city)");

        jLabel41.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel41.setText("Birthday :");

        jLabel46.setForeground(new java.awt.Color(204, 204, 204));
        jLabel46.setText("(ex-YYYY-MM-DD)");

        jLabel44.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel44.setText("Phone :");

        jLabel43.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel43.setText("Gender :");

        jLabel45.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel45.setText("NIC :");

        jLabel48.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel48.setText("UserName :");

        txtuname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtuname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtunametxtnic1ActionPerformed(evt);
            }
        });

        txtsnic.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtsnic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsnictxtnicActionPerformed(evt);
            }
        });

        txtsgender.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtsgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsgendertxtgenderActionPerformed(evt);
            }
        });

        txtsphone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtsphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsphonetxtphoneActionPerformed(evt);
            }
        });

        txtsbd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtsbd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsbdtxtbdActionPerformed(evt);
            }
        });

        txtsaddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtsaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsaddresstxtaddressActionPerformed(evt);
            }
        });

        txtlastname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtlastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlastnametxtlnameActionPerformed(evt);
            }
        });

        txtfirstname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtfirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfirstnametxtfnameActionPerformed(evt);
            }
        });

        txtstaffid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtstaffid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtstaffidtxtmemberIDFocusLost(evt);
            }
        });
        txtstaffid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstaffidtxtmemberIDActionPerformed(evt);
            }
        });

        jLabel49.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel49.setText("Password :");

        txtpword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtpword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpwordtxtnic1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel47)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtsbd, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel46)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtstaffid, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtlastname, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtsaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtsnic, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtuname, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtpword, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtsphone, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsgender, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(97, 97, 97))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(397, 397, 397))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel37)
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel44)
                            .addComponent(txtsphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtsgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel43))
                        .addGap(2, 2, 2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 12, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel38)
                            .addComponent(txtstaffid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel40)
                            .addComponent(txtfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel45)
                            .addComponent(txtsnic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel48)
                            .addComponent(txtuname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtlastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel39))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel49)
                                    .addComponent(txtpword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel42)
                                    .addComponent(txtsaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel47)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel41)
                                    .addComponent(txtsbd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(5, 5, 5)))
                        .addComponent(jLabel46)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(204, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnsave9.setBackground(new java.awt.Color(204, 204, 204));
        btnsave9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnsave9.setText("Add");
        btnsave9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsave9btnsaveActionPerformed(evt);
            }
        });

        btnsave10.setBackground(new java.awt.Color(204, 204, 204));
        btnsave10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnsave10.setText("Update");
        btnsave10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsave10btnsave1ActionPerformed(evt);
            }
        });

        btnsave11.setBackground(new java.awt.Color(204, 204, 204));
        btnsave11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnsave11.setText("Delete");
        btnsave11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsave11btnsave2ActionPerformed(evt);
            }
        });

        btnclear3.setBackground(new java.awt.Color(204, 204, 204));
        btnclear3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnclear3.setText("Clear");
        btnclear3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclear3btnclearActionPerformed(evt);
            }
        });

        btnclose3.setBackground(new java.awt.Color(204, 204, 204));
        btnclose3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnclose3.setText("Exit");
        btnclose3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclose3btncloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnsave9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsave10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnsave11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnclear3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnclose3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(btnsave9)
                .addGap(18, 18, 18)
                .addComponent(btnsave10)
                .addGap(18, 18, 18)
                .addComponent(btnsave11)
                .addGap(18, 18, 18)
                .addComponent(btnclear3)
                .addGap(18, 18, 18)
                .addComponent(btnclose3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Staff ID", "First Name", "Last Name", "Address", "Birthday", "Phone", "Gender", "NIC", "Username", "Password"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        btnsave12.setBackground(new java.awt.Color(204, 204, 204));
        btnsave12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnsave12.setText("Print Report");
        btnsave12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsave12ActionPerformed(evt);
            }
        });

        jLabel50.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel50.setText("Staff ID :");

        txtmemberID4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtmemberID4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtmemberID4FocusLost(evt);
            }
        });
        txtmemberID4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmemberID4ActionPerformed(evt);
            }
        });

        btnsave13.setBackground(new java.awt.Color(204, 204, 204));
        btnsave13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnsave13.setText("searsh");
        btnsave13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsave13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtmemberID4, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnsave13))
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnsave12)
                        .addGap(33, 33, 33))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel50)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtmemberID4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnsave13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(btnsave12)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 885, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsave9btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsave9btnsaveActionPerformed

        // TODO add your handling code here:
       try {
            String sql = "insert into staff_details(First_Name, Last_Name, Address, Birthday, Phone, Gender, NIC, Username, Password )"
                    + "values('"+txtfirstname.getText()+"','"+txtlastname.getText() +"','"+txtsaddress.getText()+"',"
                    + "'"+txtsbd.getText()+"','"+txtsphone.getText()+"','"+txtsgender.getText()+"','"+txtsnic.getText()+"',"
                    + "'"+txtuname.getText()+"','"+txtpword.getText()+"')";
            dob.connect();
            dob.insert(sql);
            dob.closeCon();
             tableload();
            
         txtstaffid.setText("");   
        txtfirstname.setText("");
        txtlastname.setText("");
        txtsaddress.setText("");
        txtsbd.setText("");
        txtsphone.setText("");
        txtsgender.setText("");
        txtsnic.setText("");
        txtuname.setText("");
        txtpword.setText("");
        
            
          
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_btnsave9btnsaveActionPerformed

    private void btnsave10btnsave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsave10btnsave1ActionPerformed
        // TODO add your handling code here:
         try {
            String sql = "update staff_details set First_Name = '" + txtfirstname.getText() + "', Last_Name = '" 
                    + txtlastname.getText() + "',Address = '" + txtsaddress.getText() + "', Birthday = '" + txtsbd.getText() + "',"
                    + "Phone = '" + txtsphone.getText() + "', Gender= '" + txtsgender.getText() + "',  NIC= '" + txtsnic.getText() + "',"
                            + "Username= '" + txtuname.getText() + "',  Password= '" + txtpword.getText() + "' Where Staff_ID = " + txtstaffid.getText();
            dob.connect();
            dob.update(sql);       
            dob.closeCon();
            
            tableload();
            
              txtstaffid.setText("");   
        txtfirstname.setText("");
        txtlastname.setText("");
        txtsaddress.setText("");
        txtsbd.setText("");
        txtsphone.setText("");
        txtsgender.setText("");
        txtsnic.setText("");
        txtuname.setText("");
        txtpword.setText("");
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnsave10btnsave1ActionPerformed

    private void btnsave11btnsave2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsave11btnsave2ActionPerformed
        // TODO add your handling code here:
         try {
             int res = JOptionPane.showConfirmDialog(null, "Do you want to Delete?",null,JOptionPane.YES_NO_OPTION);
             if(res == JOptionPane.YES_NO_OPTION){
             
            String sql = "delete from staff_details Where Staff_ID = " + txtstaffid.getText();
            dob.connect();
            dob.delete(sql);
            dob.closeCon();
            //JOptionPane.showMessageDialog(null, "Success...!");
            tableload();
            
        txtstaffid.setText("");   
        txtfirstname.setText("");
        txtlastname.setText("");
        txtsaddress.setText("");
        txtsbd.setText("");
        txtsphone.setText("");
        txtsgender.setText("");
        txtsnic.setText("");
        txtuname.setText("");
        txtpword.setText("");
            
         
             }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            // meken delete krn ek
        }
    }//GEN-LAST:event_btnsave11btnsave2ActionPerformed

    private void btnclear3btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclear3btnclearActionPerformed
        // TODO add your handling code here:
       txtstaffid.setText("");   
        txtfirstname.setText("");
        txtlastname.setText("");
        txtsaddress.setText("");
        txtsbd.setText("");
        txtsphone.setText("");
        txtsgender.setText("");
        txtsnic.setText("");
        txtuname.setText("");
        txtpword.setText("");
    }//GEN-LAST:event_btnclear3btnclearActionPerformed

    private void btnclose3btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclose3btncloseActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btnclose3btncloseActionPerformed

    private void txtunametxtnic1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtunametxtnic1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtunametxtnic1ActionPerformed

    private void txtsnictxtnicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsnictxtnicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsnictxtnicActionPerformed

    private void txtsgendertxtgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsgendertxtgenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsgendertxtgenderActionPerformed

    private void txtsphonetxtphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsphonetxtphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsphonetxtphoneActionPerformed

    private void txtsbdtxtbdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsbdtxtbdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsbdtxtbdActionPerformed

    private void txtsaddresstxtaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsaddresstxtaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsaddresstxtaddressActionPerformed

    private void txtlastnametxtlnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlastnametxtlnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlastnametxtlnameActionPerformed

    private void txtfirstnametxtfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfirstnametxtfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfirstnametxtfnameActionPerformed

    private void txtstaffidtxtmemberIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtstaffidtxtmemberIDFocusLost
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            DBClass dob=new DBClass();
            dob.connect();
            String sql="select *from member_information where Member_ID='"+txtmemberID.getText()+"'";
            // System.out.println(sql);
            ResultSet rs=dob.selectRecord(sql);
            while(rs.next())
            {

                txtfname.setText(rs.getString("First_name"));
                txtlname.setText(rs.getString("Last_name"));
                txtaddress.setText(rs.getString("Address"));
                txtbd.setText(rs.getString("Birthday"));
                txtphone.setText(rs.getString("Phone"));
                txtgender.setText(rs.getString("Gender"));
                txtnic.setText(rs.getString("NIC"));

                //txtWorkerTitle.setText(rs.getString("WORKER_TITLE"));
            }
            dob.closeCon();

        } catch (SQLException ex) {
            Logger.getLogger(StaffManagementReport.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtstaffidtxtmemberIDFocusLost

    private void txtstaffidtxtmemberIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstaffidtxtmemberIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstaffidtxtmemberIDActionPerformed

    private void txtpwordtxtnic1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpwordtxtnic1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpwordtxtnic1ActionPerformed

    private void btnsave12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsave12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsave12ActionPerformed

    private void txtmemberID4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtmemberID4FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmemberID4FocusLost

    private void txtmemberID4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmemberID4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmemberID4ActionPerformed

    private void btnsave13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsave13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsave13ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        int r = jTable2.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        
       txtstaffid.setText(model.getValueAt(r, 0).toString());
        txtfirstname.setText(model.getValueAt(r, 1).toString());       
        txtlastname.setText(model.getValueAt(r, 2).toString());
        txtsaddress.setText(model.getValueAt(r, 3).toString());
        txtsbd.setText(model.getValueAt(r, 4).toString());
        txtsphone.setText(model.getValueAt(r, 5).toString());
        txtsgender.setText(model.getValueAt(r, 6).toString());
         txtsnic.setText(model.getValueAt(r, 7).toString());
        txtuname.setText(model.getValueAt(r, 8).toString());
        txtpword.setText(model.getValueAt(r, 9).toString());
    }//GEN-LAST:event_jTable2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffManagementReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffManagementReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffManagementReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffManagementReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffManagementReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnclear1;
    private javax.swing.JButton btnclear2;
    private javax.swing.JButton btnclear3;
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btnclose1;
    private javax.swing.JButton btnclose2;
    private javax.swing.JButton btnclose3;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnsave1;
    private javax.swing.JButton btnsave10;
    private javax.swing.JButton btnsave11;
    private javax.swing.JButton btnsave12;
    private javax.swing.JButton btnsave13;
    private javax.swing.JButton btnsave2;
    private javax.swing.JButton btnsave3;
    private javax.swing.JButton btnsave4;
    private javax.swing.JButton btnsave5;
    private javax.swing.JButton btnsave6;
    private javax.swing.JButton btnsave7;
    private javax.swing.JButton btnsave8;
    private javax.swing.JButton btnsave9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtaddress1;
    private javax.swing.JTextField txtaddress2;
    private javax.swing.JTextField txtbd;
    private javax.swing.JTextField txtbd1;
    private javax.swing.JTextField txtbd2;
    private javax.swing.JTextField txtfirstname;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtfname1;
    private javax.swing.JTextField txtfname2;
    private javax.swing.JTextField txtgender;
    private javax.swing.JTextField txtgender1;
    private javax.swing.JTextField txtgender2;
    private javax.swing.JTextField txtlastname;
    private javax.swing.JTextField txtlname;
    private javax.swing.JTextField txtlname1;
    private javax.swing.JTextField txtlname2;
    private javax.swing.JTextField txtmemberID;
    private javax.swing.JTextField txtmemberID1;
    private javax.swing.JTextField txtmemberID2;
    private javax.swing.JTextField txtmemberID4;
    private javax.swing.JTextField txtnic;
    private javax.swing.JTextField txtnic1;
    private javax.swing.JTextField txtnic2;
    private javax.swing.JTextField txtnic3;
    private javax.swing.JTextField txtnic4;
    private javax.swing.JTextField txtnic5;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txtphone1;
    private javax.swing.JTextField txtphone2;
    private javax.swing.JTextField txtpword;
    private javax.swing.JTextField txtsaddress;
    private javax.swing.JTextField txtsbd;
    private javax.swing.JTextField txtsgender;
    private javax.swing.JTextField txtsnic;
    private javax.swing.JTextField txtsphone;
    private javax.swing.JTextField txtstaffid;
    private javax.swing.JTextField txtuname;
    // End of variables declaration//GEN-END:variables
}
