/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Date.DatePicker;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import utility.DBClass;

/**
 *
 * @author User
 */
public class Staff_dashboard extends javax.swing.JFrame {
    DBClass dob;

    /**
     * Creates new form Staff_dashboard
     */
    public Staff_dashboard() {
        initComponents();
        dob = new DBClass();
         showDate();
         showTime();
         showMemberCount();
          showBookCount();
           startRealTimeMemberCount();
         this.setExtendedState(StaffDashboard.MAXIMIZED_BOTH);
    }
    
    public void showDate(){
    Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyyy");
    String Dat = s.format(d);
    txtdate.setText(Dat);
    }
    
    
     public void showTime(){
   new Timer(0,new ActionListener() {
       @Override
       public void actionPerformed(ActionEvent e) {
            Date d = new Date();
            SimpleDateFormat s = new SimpleDateFormat("hh-mm-ss");
            String Tim = s.format(d);
    txttime.setText(Tim);

       }
   }).start();
    }
     
      public void startRealTimeMemberCount() {
    Timer timer = new Timer(1000, new ActionListener() { // 1000ms = 1 second
        @Override
        public void actionPerformed(ActionEvent e) {
           updateData();
        }
    });
    timer.start(); // Start the timer
}
     
      
       private void updateData() {
        showMemberCount();
        showBookCount();
       
    }
      private void showMemberCount() {
        try {
            dob.connect();
            String sql = "SELECT COUNT(*) AS total FROM members";

           
            ResultSet rs=dob.selectRecord(sql);

            if (rs.next()) {
               int count = rs.getInt("total");
                txtnoofmemmers.setText(String.valueOf(count));
            }

            
        } catch (SQLException e) {
            txtnoofmemmers.setText("Error");

        }
    }
      
     

 
       private void showBookCount() {
        try {
            dob.connect(); // Connect to the database
            String sql = "SELECT SUM(No_Of_Copies) AS total FROM add_books";

            ResultSet rs = dob.selectRecord(sql);

            if (rs.next()) {
                int totalCopies = rs.getInt("total");
                txtnoofbooks.setText(String.valueOf(totalCopies));
            }
        } catch (SQLException e) {
            txtnoofbooks.setText("Error");
        }
    }
      

 
      
   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel11 = new javax.swing.JLabel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        txtdate = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txttime = new javax.swing.JLabel();
        txtnoofmemmers = new javax.swing.JLabel();
        txtnoofbooks = new javax.swing.JLabel();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        btnsearchbooks = new javax.swing.JToggleButton();
        btnManagremember = new javax.swing.JToggleButton();
        btnmanagebooks = new javax.swing.JToggleButton();
        btnissuebooks = new javax.swing.JToggleButton();
        btnlogout = new javax.swing.JToggleButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtbooID = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtmemberID = new javax.swing.JTextField();
        txtissuedate = new javax.swing.JTextField();
        txtduedate = new javax.swing.JTextField();
        btnissue = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        kGradientPanel5 = new keeptoo.KGradientPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtmname = new javax.swing.JTextField();
        txtbname = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtbookid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtmemid = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtfine = new javax.swing.JTextField();
        txtreturndate = new javax.swing.JTextField();
        tduedate = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        kGradientPanel4 = new keeptoo.KGradientPanel();
        txtrbname = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtrmname = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        kGradientPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        kGradientPanel1.setkEndColor(new java.awt.Color(0, 153, 153));
        kGradientPanel1.setkStartColor(new java.awt.Color(153, 255, 255));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Bookmark.png"))); // NOI18N
        jLabel11.setText("Library Management System");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(407, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(319, 319, 319))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        kGradientPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        kGradientPanel2.setkEndColor(new java.awt.Color(0, 153, 153));
        kGradientPanel2.setkStartColor(new java.awt.Color(153, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Installment Plan.png"))); // NOI18N

        txtdate.setBackground(new java.awt.Color(0, 0, 0));
        txtdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtdate.setText("Date");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Clock.png"))); // NOI18N

        txttime.setBackground(new java.awt.Color(0, 0, 0));
        txttime.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txttime.setText("Time");

        txtnoofmemmers.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtnoofmemmers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/People.png"))); // NOI18N
        txtnoofmemmers.setText("10");

        txtnoofbooks.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtnoofbooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Books.png"))); // NOI18N
        txtnoofbooks.setText("12");

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtdate)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txttime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtnoofmemmers)
                .addGap(47, 47, 47)
                .addComponent(txtnoofbooks)
                .addGap(74, 74, 74))
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttime)
                            .addComponent(txtnoofmemmers)
                            .addComponent(txtnoofbooks)))
                    .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(txtdate)))
                .addContainerGap())
        );

        kGradientPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        kGradientPanel3.setkEndColor(new java.awt.Color(0, 102, 102));
        kGradientPanel3.setkStartColor(new java.awt.Color(153, 255, 255));

        btnsearchbooks.setBackground(new java.awt.Color(204, 204, 255));
        btnsearchbooks.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnsearchbooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/Search.png"))); // NOI18N
        btnsearchbooks.setText("Search Books");
        btnsearchbooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchbooksActionPerformed(evt);
            }
        });

        btnManagremember.setBackground(new java.awt.Color(204, 204, 255));
        btnManagremember.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnManagremember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Add Male User Group.png"))); // NOI18N
        btnManagremember.setText("Manage Members");
        btnManagremember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagrememberActionPerformed(evt);
            }
        });

        btnmanagebooks.setBackground(new java.awt.Color(204, 204, 255));
        btnmanagebooks.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnmanagebooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-books-48.png"))); // NOI18N
        btnmanagebooks.setText("Manage Books");
        btnmanagebooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmanagebooksActionPerformed(evt);
            }
        });

        btnissuebooks.setBackground(new java.awt.Color(204, 204, 255));
        btnissuebooks.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnissuebooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Book And Pencil.png"))); // NOI18N
        btnissuebooks.setText("Book Status");
        btnissuebooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnissuebooksActionPerformed(evt);
            }
        });

        btnlogout.setBackground(new java.awt.Color(204, 204, 255));
        btnlogout.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-logout-48.png"))); // NOI18N
        btnlogout.setText("Logout");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel3Layout = new javax.swing.GroupLayout(kGradientPanel3);
        kGradientPanel3.setLayout(kGradientPanel3Layout);
        kGradientPanel3Layout.setHorizontalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnManagremember, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnmanagebooks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnissuebooks, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(kGradientPanel3Layout.createSequentialGroup()
                        .addComponent(btnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnsearchbooks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        kGradientPanel3Layout.setVerticalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnsearchbooks, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnManagremember, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnmanagebooks, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnissuebooks, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Borrow Book.png"))); // NOI18N
        jLabel6.setText("Issue Books");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 13, 210, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Book ID :");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 92, 22));

        txtbooID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtbooID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtbooIDFocusLost(evt);
            }
        });
        txtbooID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbooIDActionPerformed(evt);
            }
        });
        jPanel5.add(txtbooID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 231, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Member ID :");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 92, 22));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Issue Date :");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 92, 22));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Due Date:");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 92, 22));

        txtmemberID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtmemberID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtmemberIDFocusLost(evt);
            }
        });
        jPanel5.add(txtmemberID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 231, -1));

        txtissuedate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel5.add(txtissuedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 231, -1));

        txtduedate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel5.add(txtduedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 231, -1));

        btnissue.setBackground(new java.awt.Color(204, 204, 204));
        btnissue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnissue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Done.png"))); // NOI18N
        btnissue.setText("Issue");
        btnissue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnissueActionPerformed(evt);
            }
        });
        jPanel5.add(btnissue, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 90, -1));

        btnclose.setBackground(new java.awt.Color(204, 204, 204));
        btnclose.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Close.png"))); // NOI18N
        btnclose.setText("Reset");
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });
        jPanel5.add(btnclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 100, -1));

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Calendar.png"))); // NOI18N
        jButton4.setText("Select Date");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, -1, -1));

        jButton6.setBackground(new java.awt.Color(204, 204, 204));
        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Calendar.png"))); // NOI18N
        jButton6.setText("Select Date");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, -1, -1));

        kGradientPanel5.setkEndColor(new java.awt.Color(204, 255, 204));
        kGradientPanel5.setkStartColor(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout kGradientPanel5Layout = new javax.swing.GroupLayout(kGradientPanel5);
        kGradientPanel5.setLayout(kGradientPanel5Layout);
        kGradientPanel5Layout.setHorizontalGroup(
            kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );
        kGradientPanel5Layout.setVerticalGroup(
            kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        jPanel5.add(kGradientPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 470, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Member Name:");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, -1, 20));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Book Name:");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, -1, -1));

        txtmname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel5.add(txtmname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, 260, -1));

        txtbname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel5.add(txtbname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 260, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Return Book.png"))); // NOI18N
        jLabel3.setText("Return Books");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 18, 224, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Book ID :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 99, -1, -1));

        txtbookid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtbookid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtbookidFocusLost(evt);
            }
        });
        txtbookid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbookidActionPerformed(evt);
            }
        });
        jPanel2.add(txtbookid, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 96, 205, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Member ID :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 149, -1, -1));

        txtmemid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtmemid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtmemidFocusLost(evt);
            }
        });
        txtmemid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmemidActionPerformed(evt);
            }
        });
        jPanel2.add(txtmemid, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 146, 205, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Issue Date :");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 194, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Due Date :");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 240, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Return Date :");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 287, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Fine :");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 334, -1, -1));

        txtfine.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtfine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfineActionPerformed(evt);
            }
        });
        jPanel2.add(txtfine, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 331, 205, -1));

        txtreturndate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtreturndate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtreturndateActionPerformed(evt);
            }
        });
        jPanel2.add(txtreturndate, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 284, 205, -1));

        tduedate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tduedate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tduedateActionPerformed(evt);
            }
        });
        jPanel2.add(tduedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 237, 205, -1));

        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 191, 205, -1));

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Search.png"))); // NOI18N
        jButton3.setText("Serch");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 146, 123, -1));

        jButton5.setBackground(new java.awt.Color(204, 204, 204));
        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Calendar.png"))); // NOI18N
        jButton5.setText("Select Date");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 284, 138, -1));

        jButton7.setBackground(new java.awt.Color(204, 204, 204));
        jButton7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Estimate.png"))); // NOI18N
        jButton7.setText("Calculate Fine");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 331, -1, -1));

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Close.png"))); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 389, 90, -1));

        jButton8.setBackground(new java.awt.Color(204, 204, 204));
        jButton8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Done.png"))); // NOI18N
        jButton8.setText("Return");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 389, -1, -1));

        kGradientPanel4.setkEndColor(new java.awt.Color(204, 255, 204));
        kGradientPanel4.setkStartColor(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout kGradientPanel4Layout = new javax.swing.GroupLayout(kGradientPanel4);
        kGradientPanel4.setLayout(kGradientPanel4Layout);
        kGradientPanel4Layout.setHorizontalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
        kGradientPanel4Layout.setVerticalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        jPanel2.add(kGradientPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 490, 370));

        txtrbname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(txtrbname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 310, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("Book Name:");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Member Name:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, -1, -1));

        txtrmname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(txtrmname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 500, 310, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(kGradientPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                    .addComponent(kGradientPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kGradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnissueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnissueActionPerformed
        // TODO add your handling code here:

        try {
            String Return_Book = "No";
            String Return_Date = "No";
            String Fine = "0.00";
            String sql = "insert into issue_book(Book_ID, Member_ID, Issue_Date, Due_Date,Return_Book, Return_Date,Fine)"
            + "values('" + txtbooID.getText() + "','" + txtmemberID.getText() + "','" + txtissuedate.getText() + "',"
            + "'" + txtduedate.getText() + "','" + Return_Book+ "','" + Return_Date+ "','" + Fine+ "')";
            dob.connect();
            dob.insert(sql);
            dob.closeCon();

            txtbooID.setText("");
            txtmemberID.setText("");
            txtissuedate.setText("");
            txtduedate.setText("");
            txtbname.setText("");
            txtmname.setText("");

        } catch (java.sql.SQLException ex) {
            Logger.getLogger(Staff_dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnissueActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        // TODO add your handling code here:
        txtbooID.setText("");
        txtmemberID.setText("");
        txtissuedate.setText("");
        txtduedate.setText("");
         txtbname.setText("");
            txtmname.setText("");
    }//GEN-LAST:event_btncloseActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        DatePicker datePicker = new DatePicker(this);
        txtduedate.setText(datePicker.setPickedDate());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        DatePicker datePicker = new DatePicker(this);
        txtissuedate.setText(datePicker.setPickedDate());
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnsearchbooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchbooksActionPerformed
        // TODO add your handling code here:
        new searchbook().setVisible(true);
    }//GEN-LAST:event_btnsearchbooksActionPerformed

    private void btnManagrememberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagrememberActionPerformed
        // TODO add your handling code here:

        new Member().setVisible(true);
    }//GEN-LAST:event_btnManagrememberActionPerformed

    private void btnmanagebooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmanagebooksActionPerformed
        // TODO add your handling code here:
        new AddbookInterface().setVisible(true);
    }//GEN-LAST:event_btnmanagebooksActionPerformed

    private void btnissuebooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnissuebooksActionPerformed
        // TODO add your handling code here:
        new IssueBook().setVisible(true);
    }//GEN-LAST:event_btnissuebooksActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new welcomepage().setVisible(true);
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void txtbookidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbookidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbookidActionPerformed

    private void txtmemidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmemidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmemidActionPerformed

    private void txtfineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfineActionPerformed

    private void txtreturndateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtreturndateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtreturndateActionPerformed

    private void tduedateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tduedateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tduedateActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            dob.connect();
            String sql = "SELECT * FROM issue_book WHERE Book_ID='"
            + txtbookid.getText()
            + "' AND Member_ID='"
            + txtmemid.getText()
            + "'";

            // System.out.println(sql);
            ResultSet rs=dob.selectRecord(sql);

            if (rs.next()) {
                jTextField3.setText(rs.getString("Issue_Date"));
                tduedate.setText(rs.getString("Due_Date"));

            }else{
                JOptionPane.showMessageDialog(null,"Sorry,Not Found");
                txtbookid.setText("");
                txtmemid.setText("");

            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        DatePicker datePicker = new DatePicker(this);
        txtreturndate.setText(datePicker.setPickedDate());
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try {
            // Date formatter
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");

            // Parse input dates
            LocalDate dueDate = LocalDate.parse(tduedate.getText(), formatter);
            LocalDate returnDate = LocalDate.parse(txtreturndate.getText(), formatter);

            // Calculate days between dates
            long daysOverdue = ChronoUnit.DAYS.between(dueDate, returnDate);

            // Calculate fine
            if (daysOverdue > 0) {
                long fine = daysOverdue * 5;
                txtfine.setText(String.valueOf(fine));
            } else {
                txtfine.setText("0"); // No fine for on-time or early returns
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Invalid date format! Please use yyyy-MM-dd.");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        txtbookid.setText("");
        txtmemid.setText("");
        jTextField3.setText("");
        tduedate.setText("");
        txtreturndate.setText("");
        txtfine.setText("");
          txtrbname.setText("");
            txtrmname.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        String Book_ID =txtbookid.getText();
        String Member_ID =txtmemid.getText();
        try {
            String sql = "UPDATE issue_book SET Return_Book = 'Yes', Return_Date='" + txtreturndate.getText() + "', Fine='" + txtfine.getText() + "' WHERE Book_ID='"
            + Book_ID
            + "' AND Member_ID='"
            + Member_ID
            + "'";

            dob.connect();
            dob.update(sql);
            dob.closeCon();

            txtbookid.setText("");
            txtmemid.setText("");
            jTextField3.setText("");
            tduedate.setText("");
            txtreturndate.setText("");
            txtfine.setText("");
             txtrbname.setText("");
            txtrmname.setText("");
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void txtbooIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbooIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbooIDActionPerformed

    private void txtbooIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtbooIDFocusLost
        // TODO add your handling code here:
        try {
             DBClass dob=new DBClass();
            dob.connect();
            String sql="select *from add_books where Book_ID ='"+txtbooID.getText()+"'";
             ResultSet rs=dob.selectRecord(sql);
            while(rs.next()){
             txtbname.setText(rs.getString("Name"));
            }
        } catch (Exception ex) {
            Logger.getLogger(Staff_dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtbooIDFocusLost

    private void txtmemberIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtmemberIDFocusLost
        // TODO add your handling code here:
          try {
             DBClass dob=new DBClass();
            dob.connect();
            String sql="select *from members where Member_ID ='"+txtmemberID.getText()+"'";
             ResultSet rs=dob.selectRecord(sql);
            while(rs.next()){
             txtmname.setText(rs.getString("First_name"));
            }
        } catch (Exception ex) {
            Logger.getLogger(Staff_dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtmemberIDFocusLost

    private void txtbookidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtbookidFocusLost
        // TODO add your handling code here:
         try {
             DBClass dob=new DBClass();
            dob.connect();
            String sql="select *from add_books where Book_ID ='"+txtbookid.getText()+"'";
             ResultSet rs=dob.selectRecord(sql);
            while(rs.next()){
             txtrbname.setText(rs.getString("Name"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Staff_dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtbookidFocusLost

    private void txtmemidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtmemidFocusLost
        // TODO add your handling code here:
         try {
             DBClass dob=new DBClass();
            dob.connect();
            String sql="select *from members where Member_ID ='"+txtmemid.getText()+"'";
             ResultSet rs=dob.selectRecord(sql);
            while(rs.next()){
             txtrmname.setText(rs.getString("First_name"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Staff_dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtmemidFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Staff_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Staff_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Staff_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Staff_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Staff_dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnManagremember;
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btnissue;
    private javax.swing.JToggleButton btnissuebooks;
    private javax.swing.JToggleButton btnlogout;
    private javax.swing.JToggleButton btnmanagebooks;
    private javax.swing.JToggleButton btnsearchbooks;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField3;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private keeptoo.KGradientPanel kGradientPanel3;
    private keeptoo.KGradientPanel kGradientPanel4;
    private keeptoo.KGradientPanel kGradientPanel5;
    private javax.swing.JTextField tduedate;
    private javax.swing.JTextField txtbname;
    private javax.swing.JTextField txtbooID;
    private javax.swing.JTextField txtbookid;
    private javax.swing.JLabel txtdate;
    private javax.swing.JTextField txtduedate;
    private javax.swing.JTextField txtfine;
    private javax.swing.JTextField txtissuedate;
    private javax.swing.JTextField txtmemberID;
    private javax.swing.JTextField txtmemid;
    private javax.swing.JTextField txtmname;
    private javax.swing.JLabel txtnoofbooks;
    private javax.swing.JLabel txtnoofmemmers;
    private javax.swing.JTextField txtrbname;
    private javax.swing.JTextField txtreturndate;
    private javax.swing.JTextField txtrmname;
    private javax.swing.JLabel txttime;
    // End of variables declaration//GEN-END:variables
}
